version = 1

test_patterns = ["tests/*"]

exclude_patterns = [
    "scripts/*",
    ".circleci/*",
    "docs/*",
    ".code2pdf",
    ".env",
    ".gitattributes",
    ".gitignore",
    "*.yml",
    "*.yaml",
    "*.txt",
    "*.toml",
    "*.ini",
    "*.json",
    "*.tf",
    "Dockerfile"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.6.9"
