language: python
python: 3.7
services:
  - docker

before_install:
  - docker build --build-arg target=test -t mormo .

script:
  - docker run --rm mormo pytest
  - docker run mormo run -i tests/data/openapi/json/openapi.json -o o.json --host http://localhost:8001 --test -t mormo.yaml --verbose
