language: python
python: 3.7
services:
  - docker

before_install:
  - docker build --build-arg target=test -t mormo .

script:
  - docker run --rm mormo pytest
  - docker run --rm mormo mormo run -i openapi.json --host http://127.0.0.1:8001 --test_mormo_api -t mormo.yaml --verbose
