language: python
python: 3.7
services:
  - docker

jobs:
  include:
    - stage: "Docker"
      name: "Docker Build"
      script: docker build -t joeystevens00/mormo:api .
    - script:
        - docker login --username joeystevens00 --password $DOCKER_HUB_TOKEN
        - docker image push joeystevens00/mormo:api
      name: "Upload image to Docker Hub"
    - script: docker-compose up -d
      name: "Bring up containers"
    - stage: "Test"
      script: docker-compose exec app pip install pytest pytest-cov coveralls
      name: "Install test dependencies"
    - script: docker-compose exec app bash -c "export COVERALLS_REPO_TOKEN=$REPO_TOKEN; coveralls"
      name: "Upload test coverage"
    - script: docker-compose exec app pytest --cov=mormo
      name: "Unit Test"
    - script:
      - docker-compose exec app bash -c 'curl 127.0.0.1:8001/openapi.json > openapi.json'
      - docker-compose exec app mormo run -i openapi.json --test --host http://127.0.0.1:8001 -t mormo.yaml --verbose
      name: "Test API using CLI"
