services:
  - docker

jobs:
  include:
    - stage: "Docker Image"
      install: docker build -t joeystevens00/mormo:api .
      script: docker login --username joeystevens00 --password $DOCKER_HUB_TOKEN
      after_success: docker image push joeystevens00/mormo:api
      name: "Build and Upload"
    - stage: "Docker Container"
      install: docker-compose up -d
      script: docker-compose exec app pip install pytest pytest-cov coveralls
      name: "Install test dependencies"
    - stage: "Unit Test"
      script: docker-compose exec app pytest --cov=mormo
      after_success: docker-compose exec app bash -c "export COVERALLS_REPO_TOKEN=$REPO_TOKEN; coveralls"
      name: "Test and Upload test coverage"
    - stage: "Integration Test"
      before_script: docker-compose exec app bash -c 'curl 127.0.0.1:8001/openapi.json > openapi.json'
      script: docker-compose exec app mormo run -i openapi.json --test --host http://127.0.0.1:8001 -t mormo.yaml --verbose
      name: "Test API using CLI"
