version: '3.3'

services:
  redis:
    image: redis
  app:
    depends_on:
      - redis
    image: "${MORMO_IMAGE:-joeystevens00/mormo:api}"
    restart: always
    ports:
      - "${EXPOSE_PORT:-8001}:8001"
    environment:
      - REDIS_HOST=redis
    build:
      context: .
      dockerfile: Dockerfile
      args:
        target: api
