version: '3'

services:
  redis:
    image: redis
  app:
    depends_on:
      - redis
    image: joeystevens00/mormo:api
    restart: always
    ports:
      - 8001:8001
    environment:
      - REDIS_HOST=redis
