#!/bin/bash
exec < /dev/tty

# Get the current branch name
branch_name=$(git branch | grep "*" | sed "s/\* //")

# Get the name of the branch that was just merged
reflog_message=$(git reflog -1)
merged_branch_name=$(echo $reflog_message | cut -d" " -f 4 | sed "s/://")

if [[ "$branch_name" == "master" ]]; then
  make coverage coveralls
fi

make update_badge_branches
git commit README.md docs/src/index.rst -m "Update badge branch targets to target branch $branch_name"
#git push
