version: 2
jobs:
  build:
    docker:
      - image: themattrix/tox
    steps:
      - checkout
      - run: apt-get update && apt-get upgrade -y
      - run: apt-get install npm -y
      - run: npm install -g newman
      - run: tox
